name: tests-auth

on:
  pull_request:
    path:
      - 'auth/**'

jobs:
  build:
    runs-on: ubunta-latest
    steps:
      - uses: action/checkout@v2
      - run: cd auth npm install && npm run test:ci
